# Generated by Django 3.1.4 on 2021-01-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Género'),
        ),
    ]
